### ISSUE TITLE
Adding separate start of docker container

### ISSUE THREAD

**Issue by GustafNi** [duartemendes/aws-sam-api-proxy#4]
Hi. 
I have an issue when i try to run this in a docker-compose whit some other services. I have a sam-api-proxy image being built and run as a docker container. 
The problem is the automated start of the lambda container. It would be nice to be able to start the lambda container that the proxy is forwarding to separately, so i can configure it and run it inside my docker-compose environment. 
 Now when I run sam-api-proxy inside a docker container, the lambda container that is started automatically doesn't have access to the filesystem inside the sam-api-proxy container.

It could also be that I'm missing something, I'm fairly new to using docker. 
Apart from my issue, this works really great just running locally for testing. Nice work

**Comment by duartemendes** [comment]
Hi @GustafNi , thank you.

Starting the lambda containers automatically is one of the advantages of sam-api-proxy. Another reason why it does this is to reproduce `sam local start-api` behaviour.

Could you describe how would you solve your problem if you were using sam cli?

It sounds like you might need to use volumes in your docker-compose?

**Comment by GustafNi** [comment]
Hi @duartemendes and thanks for your answer. 

When i used sam cli, i just pulled an image of it in my docker-compose and had no problems mounting the volumes there.
Now i have a dockerfile with an image of the sam-api-proxy, and when it builds and then run a lambda container I either have trouble connecting to it (localhost:3000) or, as you mentioned,  trouble with the mounted volumes. 

I indeed think that getting the volume mounted the right way is the issue here, like you pointed out, and not a problem with the api-sam-proxy.  Thank you for that and pointing me in the right direction. As i said, I'm not too familiar with docker yet :)

I'm closing this issue.
